version: '3.7'

services:

  database:
    container_name: database
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  cloudstorage:
    container_name: cloudstorage
    build: .
    links:
      - database
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
    depends_on:
      - database

  front:
    build:
      context: cloud-storage-frontend
      dockerfile: Dockerfile
    container_name: FRONT

    ports:
      - '8081:8080'